### ISSUE TITLE
После обновления на Yii 2.0.14 выдает ошибку

### ISSUE THREAD

**Issue by webspec2012** [yiisoft/yii2-mongodb#249]
```
2018-02-21 11:46:51 [5a65db240a64100202b7ca65][ictb38tvmfqvh09bnopant84no][error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: yii\mongodb\Connection::useMaster() in /htdocs/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /htdocs/vendor/yiisoft/yii2/validators/ExistValidator.php(253): yii\base\Component->__call('useMaster', Array)
#1 /htdocs/vendor/yiisoft/yii2/validators/ExistValidator.php(164): yii\validators\ExistValidator->valueExists('\\backend\\models...', Object(common\models\ModelQuery), Array)
#2 /htdocs/vendor/yiisoft/yii2/validators/ExistValidator.php(108): yii\validators\ExistValidator->checkTargetAttributeExistence(Object(backend\models\document\News), 'tagsIds')
#3 /htdocs/vendor/yiisoft/yii2/validators/Validator.php(267): yii\validators\ExistValidator->validateAttribute(Object(backend\models\document\News), 'tagsIds')
#4 /htdocs/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(backend\models\document\News), Array)
#5 /htdocs/vendor/yiisoft/yii2/db/BaseActiveRecord.php(729): yii\base\Model->validate(Array)
#6 /htdocs/vendor/yiisoft/yii2/db/BaseActiveRecord.php(672): yii\db\BaseActiveRecord->update(true, NULL)
#7 /htdocs/backend/actions/UpdateAction.php(70): yii\db\BaseActiveRecord->save()
#8 [internal function]: backend\actions\UpdateAction->run('5a785c6a08cecb0...')
#9 /htdocs/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)
#10 /htdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)
#11 /htdocs/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('update', Array)
#12 /htdocs/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('news/update', Array)
#13 /htdocs/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 /htdocs/common/config/bootstrap.php(17): yii\base\Application->run()
#15 /htdocs/backend/web/index.php(14): require('/opt/projects/k...')
#16 {main}
```

**Comment by klimov-paul** [comment]
Relates https://github.com/yiisoft/yii2/pull/15664/files

**Comment by klimov-paul** [comment]
Migrated to https://github.com/yiisoft/yii2/issues/15726
