### ISSUE TITLE
save method not working !

### ISSUE THREAD

**Issue by ziaratban** [yiisoft/yii2-mongodb#289]
when i call `save()` method in `yii\mongodb\ActiveRecord` , i give this errors :
```
Error: Call to a member function insert() on string in /main/kernel/vendor/yiisoft/yii2-mongodb/ActiveRecord.php:230
Stack trace:
#0 /main/kernel/vendor/yiisoft/yii2-mongodb/ActiveRecord.php(208): yii\mongodb\ActiveRecord->insertInternal(NULL)
#1 /main/kernel/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\mongodb\ActiveRecord->insert(true, NULL)
#2 /main/kernel/modules/x/controllers/ApiController.php(38): yii\db\BaseActiveRecord->save()
```

Test class:
```php
class Test extends yii\mongodb\ActiveRecord{

    public function Behaviors():array {
        return [
            'typecast' => [
                'class' => yii\behaviors\AttributeTypecastBehavior::ClassName(),
                'attributeTypes' => [
                    'fint' => yii\behaviors\AttributeTypecastBehavior::TYPE_INTEGER,
                    'fbool' => yii\behaviors\AttributeTypecastBehavior::TYPE_BOOLEAN,
                    'ffloat' => yii\behaviors\AttributeTypecastBehavior::TYPE_FLOAT,

                ],
                'typecastAfterFind' => true,
            ]
        ];
    }

    public static function GetDB(){
        return new yii\mongodb\Connection([
            'dsn' => 'mongodb://admin:123@127.0.0.1:27017/kernel',
        ]);
    }
    
    public static function GetCollection(){
        return 'clt_a';
    }
    
    public function Attributes(){
        return ['_id','fint','fbool','ffloat','fstring'];
    }
}
```

usage:
```php
$test = new Test();
$test->fint = 1;
$test->fbool = true;
$test->ffloat = 1.123456789;
$test->fstring = 'abcdef';
$test->save(); # <- error
```

**Comment by ziaratban** [comment]
oops !!!
name of `GetCollection()` method  is mistake :/
after rename to `collectionName()`, Everything worked.
but why without `collectionName()` method not working ?

**Comment by ziaratban** [comment]
ooops. no bug.
in my `hello world` project i made mistake use `GetCollection` instead of `collectionName`.
