### ISSUE TITLE
Failed to send "insert" command with database "NAME": malformed server message

### ISSUE THREAD

**Issue by vistarsvo** [yiisoft/yii2-mongodb#371]
I use docker and install mongo in isolated container (try to use 6 and 7th versions).
When i try to bulk insert 1...100 documents in 5-10 threads (using forks) i have random errors....
 - I try to change mongod wiredTiger cache size - no effect
 - try to change compression, document structure (even only one field)
 -  try to change read/write socket timeout, other connection options
 - 'typeMap' => [
                'array' => BSONArray::class,
                'document' => BSONDocument::class,
                'root' => BSONDocument::class,
            ],
- change pecl lib versions )))
... all of this has no effect.
!But, using try...catch and repeat insert throws duplicate key error. Interesting, but all 100% records inserted successfully.

When i try to use mongodb/mongodb, any errors. All work perfect.
Few hours and i don't understad "WHY" and how to understand and fix this...

### What steps will reproduce the problem?
1. Create any collection
2. Create mongoDb connection
3. Start main process with few forks (5-10)
4. Just use \Yii::$app->mongoDb->getCollection('some_collection') ->batchInsert($documents);

### What's expected?
No errors :)

### What do you get instead?
1st error:

```
Error: Bulk write failed due to previous MongoDB\Driver\Exception\RuntimeException: Failed to send "insert" command with database "NAME": malformed server message
1st Error trace: #0 /project/vendor/yiisoft/yii2-mongodb/src/Command.php(522): yii\mongodb\Command->executeBatch('data_10...', Array, Array)
#1 /project/vendor/yiisoft/yii2-mongodb/src/Collection.php(300): yii\mongodb\Command->batchInsert('data_10...', Array, Array, Array)
#2 /project/console/controllers/test/__/MongoController.php(315): yii\mongodb\Collection->batchInsert(Array, Array, Array)
```

After that:

```
Bulk write failed due to previous MongoDB\Driver\Exception\ConnectionTimeoutException: Failed to send "insert" command with database "NAME": Failed to read 18806 bytes: socket error or timeout
1st Error trace: #0 /project/vendor/yiisoft/yii2-mongodb/src/Command.php(522): yii\mongodb\Command->executeBatch('data_10...', Array, Array)
#1 /project/vendor/yiisoft/yii2-mongodb/src/Collection.php(300): yii\mongodb\Command->batchInsert('data_10...', Array, Array, Array)
#2 /project/console/controllers/test/__/MongoController.php(315): yii\mongodb\Collection->batchInsert(Array, Array, Array)
(.... next lines with internal project structure was truncated) 
```

### Additional info

Yii version    2.0.41.1
Yii MongoDB version 3.0.1 
MongoDB server version 7.0.4 (also try 6.0.12)
PHP version  7.4
Operating system  Ubuntu 23.10 (docker images 7.0.4 and 6.0.12 jammy)

**Comment by vistarsvo** [comment]
Nope. Same error. it seems, something i am doing wrong (
